config/routes.rb
Gsm::Application.routes.draw do
  resources :usersampdescs
  resources :usermodules
  resources :users
  resources :contacts do
  member do
    get :mail
  end
end

  resources :logins
  resources :samples do
  member do
    get :download
  end
end

  resources :dashboards do
  member do
    get :download
  end

end

  match '/create_userdesc' => 'samples#create_userdesc', :as => 'create_userdesc'
  match '/update_sample' => 'samples#update_sample', :as => 'update_sample'
  match '/contact_mail' => 'contacts#contact_mail', :as => 'contact_mail'

end

app/models/login.rb
class Login < ActiveRecord::Base
  attr_accessible :name, :password

    def Login.authenticate(name, password)
	  if user = find_by_name(name)
	    if user.password == password
	      user
	    end
	  end
	end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
	def new
		# @login = Login.all
  end
  
  def create
    if user = Login.authenticate(params[:name], params[:password])
      session[:user_id] = user.id
      redirect_to dashboards_path, notice: "Logged in!"
    elsif user = User.authenticate(params[:name], params[:password])
      session[:user_id] = user.id
      redirect_to dashboards_path, notice: "Logged in!"
    else
      # flash.now.alert = "Email or password is invalid"
      redirect_to new_login_path, notice: "Email or password is invalid"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to new_login_path, notice: "Logged out!"
  end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/new.html.erb
<div class="container-fluid">
		<div class="row-fluid">
		
			<div class="row-fluid">
				<div class="span12 center login-header">
					<h2>Welcome</h2>
				</div><!--/span-->
			</div><!--/row-->
			
			<div class="row-fluid">
				<div class="well span5 center login-box">
					<div class="alert alert-info">
						Please login with your Username and Password.
					</div>
					<%= form_tag logins_path do %>
						<fieldset>
							<div class="input-prepend" title="Username" data-rel="tooltip">
								<span class="add-on"><i class="icon-user"></i></span><%= text_field_tag :name, params[:name] %>
							</div>
							<div class="clearfix"></div>

							<div class="input-prepend" title="Password" data-rel="tooltip">
								<span class="add-on"><i class="icon-lock"></i></span><%= password_field_tag :password %>
							</div>
							<div class="clearfix"></div>

							<p class="center span5">
							<button type="submit" class="btn btn-primary">Login</button>
							</p>
						</fieldset>
					<% end %>
				</div><!--/span-->
			</div><!--/row-->
				</div><!--/fluid-row-->
		
	</div><!--/.fluid-container-->