config/routes.rb
Gsm::Application.routes.draw do
  resources :usersampdescs
  resources :usermodules
  resources :users
  resources :contacts do
  member do
    get :mail
  end
end

  resources :logins
  resources :samples do
  member do
    get :download
  end
end

  resources :dashboards do
  member do
    get :download
  end

end

  match '/create_userdesc' => 'samples#create_userdesc', :as => 'create_userdesc'
  match '/update_sample' => 'samples#update_sample', :as => 'update_sample'
  match '/contact_mail' => 'contacts#contact_mail', :as => 'contact_mail'

end

app/models/usersampdesc.rb
class Usersampdesc < ActiveRecord::Base
  belongs_to :sample
  attr_accessible :desc, :samp_file_name, :user_id
  has_attached_file :samp_file_name,
                    :url  => "/assets/userdescupload/:id/:style/:basename.:extension",
                    :path => ":rails_root/app/assets/userdescupload/:id/:style/:basename.:extension"
end

app/controllers/usersampdescs_controller.rb
class UsersampdescsController < ApplicationController
  # GET /usersampdescs
  # GET /usersampdescs.json
  def index
    @usersampdescs = Usersampdesc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usersampdescs }
    end
  end

  # GET /usersampdescs/1
  # GET /usersampdescs/1.json
  def show
    @usersampdesc = Usersampdesc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usersampdesc }
    end
  end

  # GET /usersampdescs/new
  # GET /usersampdescs/new.json
  def new
    @usersampdesc = Usersampdesc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usersampdesc }
    end
  end

  # GET /usersampdescs/1/edit
  def edit
    @usersampdesc = Usersampdesc.find(params[:id])
  end

  # POST /usersampdescs
  # POST /usersampdescs.json
  def create
    @usersampdesc = Usersampdesc.new(params[:usersampdesc])

    respond_to do |format|
      if @usersampdesc.save
        format.html { redirect_to @usersampdesc, notice: 'Usersampdesc was successfully created.' }
        format.json { render json: @usersampdesc, status: :created, location: @usersampdesc }
      else
        format.html { render action: "new" }
        format.json { render json: @usersampdesc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usersampdescs/1
  # PUT /usersampdescs/1.json
  def update
    @usersampdesc = Usersampdesc.find(params[:id])

    respond_to do |format|
      if @usersampdesc.update_attributes(params[:usersampdesc])
        format.html { redirect_to @usersampdesc, notice: 'Usersampdesc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usersampdesc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usersampdescs/1
  # DELETE /usersampdescs/1.json
  def destroy
    @usersampdesc = Usersampdesc.find(params[:id])
    @usersampdesc.destroy

    respond_to do |format|
      format.html { redirect_to usersampdescs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/usersampdescs_helper.rb
module UsersampdescsHelper
end

app/views/usersampdescs/_form.html.erb
<%= form_for(@usersampdesc) do |f| %>
  <% if @usersampdesc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usersampdesc.errors.count, "error") %> prohibited this usersampdesc from being saved:</h2>

      <ul>
      <% @usersampdesc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sample %><br />
    <%= f.text_field :sample %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usersampdescs/edit.html.erb
<h1>Editing usersampdesc</h1>

<%= render 'form' %>

<%= link_to 'Show', @usersampdesc %> |
<%= link_to 'Back', usersampdescs_path %>

app/views/usersampdescs/index.html.erb
<h1>Listing usersampdescs</h1>

<table>
  <tr>
    <th>Sample</th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usersampdescs.each do |usersampdesc| %>
  <tr>
    <td><%= usersampdesc.sample %></td>
    <td><%= usersampdesc.desc %></td>
    <td><%= link_to 'Show', usersampdesc %></td>
    <td><%= link_to 'Edit', edit_usersampdesc_path(usersampdesc) %></td>
    <td><%= link_to 'Destroy', usersampdesc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Usersampdesc', new_usersampdesc_path %>

app/views/usersampdescs/new.html.erb
<h1>New usersampdesc</h1>

<%= render 'form' %>

<%= link_to 'Back', usersampdescs_path %>

app/views/usersampdescs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sample:</b>
  <%= @usersampdesc.sample %>
</p>

<p>
  <b>Desc:</b>
  <%= @usersampdesc.desc %>
</p>


<%= link_to 'Edit', edit_usersampdesc_path(@usersampdesc) %> |
<%= link_to 'Back', usersampdescs_path %>